"""WAF / CDN / edge-protection fingerprint database.

Signals are drawn from publicly documented patterns and validated against
captured responses in ``tests/fixtures/``. Every entry is expected to be
backed by a real capture before it earns a weight.

Provenance: the signals below were written from publicly documented vendor
response patterns, not copied from another project. The planned systematic
import from permissively-licensed upstream databases (wafw00f, identYwaf,
cdncheck, Awesome-WAF) will carry per-entry ``source`` attribution and the
license notices recorded in NOTICE.

This database is not exhaustive and is not vendor-endorsed. Header keys ending
in ``*`` are prefix matches; a needle of ``""`` matches on header presence alone.
"""

from typing import Any

# Fingerprint database
FINGERPRINTS: list[dict[str, Any]] = [
    {
        "vendor": "Cloudflare (edge firewall/CDN)",
        "header_contains": [
            ("server", "cloudflare"),
            ("cf-ray", ""),
            ("cf-cache-status", ""),
            ("cf-mitigated", ""),
        ],
        "cookie_contains": ["__cfduid", "__cf_bm", "cf_clearance", "cf_ob_info", "cf_use_ob"],
        "body_contains": ["cloudflare", "attention required", "checking your browser"],
    },
    {
        "vendor": "Akamai (edge)",
        # Real Akamai headers are suffixed (x-akamai-transformed, x-akamai-request-id),
        # so these must be prefix matches, not exact keys.
        "header_contains": [
            ("server", "akamai"),
            ("x-akamai*", ""),
            ("akamai-grn", ""),
            ("x-check-cacheable", ""),
        ],
        "cookie_contains": ["ak_bmsc", "bm_sv", "bm_mi", "akaalb_", "aka_a2", "_abck"],
        "body_contains": ["akamai", "reference #"],
    },
    {
        "vendor": "Imperva/Incapsula",
        "header_contains": [
            ("x-iinfo", ""),
            ("x-cdn", "incapsula"),
        ],
        "cookie_contains": ["incap_ses", "visid_incap", "nlbi_"],
        "body_contains": ["incapsula", "request blocked", "powered by imperva"],
    },
    {
        "vendor": "Sucuri",
        "header_contains": [
            ("x-sucuri-id", ""),
            ("x-sucuri-cache", ""),
            ("server", "sucuri"),
        ],
        "cookie_contains": ["sucuri_cloudproxy_uuid"],
        "body_contains": ["sucuri website firewall", "access denied - sucuri"],
    },
    {
        "vendor": "ModSecurity (various vendors)",
        "header_contains": [
            ("x-modsecurity*", ""),
            ("x-powered-by", "mod_security"),
            ("server", "mod_security"),
        ],
        "cookie_contains": [],
        "body_contains": ["mod_security", "modsecurity", "not acceptable"],
    },
    {
        "vendor": "F5 (BIG-IP ASM/Advanced WAF)",
        "header_contains": [
            ("x-asm*", ""),
            ("x-waf", "f5"),
            ("x-cnection", "close"),
        ],
        # Real BIG-IP cookies: BIGipServer<pool>, TS<hex>, MRHSession, LastMRH_Session.
        # "ts01"/"ts02" were never real and are dropped.
        "cookie_contains": ["bigipserver", "f5avr", "mrhsession", "lastmrh_session"],
        "body_contains": ["the requested url was rejected", "your support id is"],
    },
    {
        "vendor": "AWS (CloudFront/AWS WAF)",
        "header_contains": [
            ("x-amz-cf-id", ""),
            ("x-amz-cf-pop", ""),
            ("via", "cloudfront"),
            ("server", "cloudfront"),
        ],
        "cookie_contains": ["aws-waf-token"],
        "body_contains": ["generated by cloudfront", "request blocked"],
    },
    {
        "vendor": "Fastly",
        "header_contains": [
            ("x-served-by", "cache-"),
            ("x-fastly*", ""),
            ("fastly-restarts", ""),
        ],
        "cookie_contains": [],
        "body_contains": ["fastly error"],
    },
]
