# SPDX-License-Identifier: Apache-2.0
#
# The fingerprint database is licensed Apache-2.0 rather than MIT (which covers
# the rest of edgeprint), because it is a compilation that aggregates material
# under BSD-3-Clause, MIT and Apache-2.0 terms. Apache-2.0 absorbs all three
# coherently; MIT cannot relabel Apache-2.0 material. See LICENSE-APACHE and NOTICE.
"""WAF / CDN / edge-protection fingerprint database.

Signals are drawn from publicly documented patterns and validated against
captured responses in ``tests/fixtures/``. Every entry is expected to be
backed by a real capture before it earns a weight.

Provenance: the signals below were written from publicly documented vendor
response patterns, not copied from another project. The planned systematic
import from permissively-licensed upstream databases (wafw00f, identYwaf,
cdncheck, Awesome-WAF) will carry per-entry ``source`` attribution and the
license notices recorded in NOTICE.

This database is not exhaustive and is not vendor-endorsed. Header keys ending
in ``*`` are prefix matches; a needle of ``""`` matches on header presence alone.
"""

from typing import Any

# Fingerprint database
FINGERPRINTS: list[dict[str, Any]] = [
    {
        "vendor": "Cloudflare (edge firewall/CDN)",
        # Presence of cf-ray proves the CDN edge, not that filtering is enabled.
        "layers": ["cdn"],
        # Signals that additionally prove a filtering decision was made.
        "signal_layers": {"cf-mitigated": "waf"},
        "header_contains": [
            ("server", "cloudflare"),
            ("cf-ray", ""),
            ("cf-cache-status", ""),
            ("cf-mitigated", ""),
        ],
        "cookie_contains": ["__cfduid", "__cf_bm", "cf_clearance", "cf_ob_info", "cf_use_ob"],
        "body_contains": ["attention required", "checking your browser"],
    },
    {
        "vendor": "Akamai (edge)",
        # Real Akamai headers are suffixed (x-akamai-transformed, x-akamai-request-id),
        # so these must be prefix matches, not exact keys.
        "layers": ["cdn"],
        # _abck is set by Akamai Bot Manager, a distinct control from the CDN.
        "signal_layers": {"_abck": "bot", "ak_bmsc": "bot", "bm_sv": "bot", "bm_mi": "bot"},
        "header_contains": [
            ("server", "akamai"),
            ("x-akamai*", ""),
            ("akamai-grn", ""),
            ("x-check-cacheable", ""),
        ],
        "cookie_contains": ["ak_bmsc", "bm_sv", "bm_mi", "akaalb_", "aka_a2", "_abck"],
        "body_contains": ["akamai"],
    },
    {
        "vendor": "Imperva/Incapsula",
        "layers": ["waf"],
        "header_contains": [
            ("x-iinfo", ""),
            ("x-cdn", "incapsula"),
        ],
        "cookie_contains": ["incap_ses", "visid_incap", "nlbi_"],
        # "request blocked" was listed here, but it is also a generic BLOCK_PATTERN
        # and a stock phrase on many origins. A signal that generic cannot serve as
        # vendor evidence, and letting it do so allowed a block page to corroborate
        # itself into a false positive.
        "body_contains": ["incapsula", "powered by imperva"],
    },
    {
        "vendor": "Sucuri",
        "layers": ["waf"],
        "header_contains": [
            ("x-sucuri-id", ""),
            ("x-sucuri-cache", ""),
            ("server", "sucuri"),
        ],
        "cookie_contains": ["sucuri_cloudproxy_uuid"],
        "body_contains": ["sucuri website firewall", "access denied - sucuri"],
    },
    {
        "vendor": "ModSecurity (various vendors)",
        "layers": ["waf"],
        "header_contains": [
            ("x-modsecurity*", ""),
            ("x-powered-by", "mod_security"),
            ("server", "mod_security"),
        ],
        "cookie_contains": [],
        "body_contains": ["mod_security", "modsecurity"],
    },
    {
        "vendor": "F5 (BIG-IP ASM/Advanced WAF)",
        "layers": ["waf"],
        "header_contains": [
            ("x-asm*", ""),
            ("server", "bigip"),
            ("x-cnection", "close"),
        ],
        # BIG-IP ASM does set TS<hex> persistence cookies, but "ts" is far too short
        # to use as a name prefix without firing on unrelated cookies; the original
        # "ts01"/"ts02" entries were arbitrary instances rather than real patterns.
        # Matching them safely needs regex support in the fingerprint schema.
        "cookie_contains": ["bigipserver", "f5avr", "mrhsession", "lastmrh_session"],
        "body_contains": ["the requested url was rejected", "your support id is"],
    },
    {
        "vendor": "AWS CloudFront (CDN)",
        "layers": ["cdn"],
        "header_contains": [
            ("x-amz-cf-id", ""),
            ("x-amz-cf-pop", ""),
            ("via", "cloudfront"),
            ("server", "cloudfront"),
        ],
        "cookie_contains": [],
        "body_contains": ["generated by cloudfront"],
    },
    {
        "vendor": "AWS WAF",
        "layers": ["waf"],
        "header_contains": [
            ("x-amzn-waf*", ""),
        ],
        "cookie_contains": ["aws-waf-token"],
        "body_contains": [],
    },
    {
        "vendor": "Fastly",
        "layers": ["cdn"],
        "header_contains": [
            ("x-served-by", "cache-"),
            ("x-fastly*", ""),
            ("fastly-restarts", ""),
        ],
        "cookie_contains": [],
        "body_contains": ["fastly error"],
    },
]
